函数中包含有lambda表达式，其表达式需要在函数外定义

如：test(var str: String, callback: (age: Int, name: String) -> Unit) {

}

test("you") {age, name -> 
    if (age == 12) {
        // ...
    }

    if (name == "Chris") {
        // ...
    }

}


# runCatching

runCatching {

}.onSuccess {

}.onFailure {

}

在 Kotlin 中使用异常处理的方式是使用 runCatching 函数，这其实是一个高阶函数。

```

    RetrofitUtil.getInstance().callAppData(call, object : NetListener {
            override fun onSuccess(message: String) {
                Log.d(TAG, "onSuccess() called with: message = $message")
              
                val result = message.runCatching {
                    val bean = GsonUtils.fromJson<CollectionBean>(message, CollectionBean::class.java)
                    return@runCatching bean
                }.onSuccess {
                    Log.i(TAG, "onSuccess: ")
                }.onFailure {
                    Log.i(TAG, "onFailure: ")
                }

                val orNull = result.getOrNull()
                val defaultValue = result.getOrDefault(CollectionBean())

                val orThrow = result.getOrThrow()
                val result3 = result.getOrElse {
                    Log.i(TAG, "onFail: 异常了")
                }

            }

            override fun onFailed(message: String?) {
                Log.d(TAG, "onFailed() called with: message = $message")
            }
        })

```